name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3', '3.4', 'head']
        simplecov: [simplecov_0_x, simplecov_1_x]
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.simplecov }}.gemfile
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Run tests
      env:
        COVERAGE: true
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: bundle exec rspec

    - name: Upload coverage to Coveralls
      if: matrix.ruby-version == '3.3' && matrix.simplecov == 'simplecov_1_x'
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
